export const phaseList = [
  {
    id: "TASK-8782",
    phase: "PHASE 1",
    initialbudget: "123456567",
    usedbudget: "232,000 Birr",
    allocatedtime: "12 months",
    remainingtime: "6 months",
    progressreport: 60,
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    phase: "PHASE 2",
    initialbudget: "123456567",
    usedbudget: "1,000,000.00 Birr",
    allocatedtime: "12 months",
    remainingtime: "6 months",
    progressreport: 60,
    status: "completed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    phase: "PHASE 3",
    initialbudget: "123456567",
    usedbudget: "152 Laptops",
    allocatedtime: "12 months",
    remainingtime: "6 months",
    progressreport: 60,
    status: "delayed",
    priority: "LOW",
  },
  {
    id: "TASK-8782",
    phase: "PHASE 4",
    initialbudget: "123456567",
    usedbudget: "232,000 Birr",
    allocatedtime: "12 months",
    remainingtime: "6 months",
    progressreport: 60,
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    phase: "PHASE 5",
    initialbudget: "123456567",
    usedbudget: "1,000,000.00 Birr",
    allocatedtime: "12 months",
    remainingtime: "6 months",
    progressreport: 60,
    status: "delayed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    phase: "PHASE 6",
    initialbudget: "123456567",
    usedbudget: "152 Laptops",
    allocatedtime: "12 months",
    remainingtime: "6 months",
    progressreport: 60,
    status: "completed",
    priority: "LOW",
  },
  {
    id: "TASK-8782",
    phase: "PHASE 7",
    initialbudget: "123456567",
    usedbudget: "232,000 Birr",
    allocatedtime: "12 months",
    remainingtime: "6 months",
    progressreport: 60,
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    phase: "PHASE 10",
    initialbudget: "123456567",
    usedbudget: "1,000,000.00 Birr",
    allocatedtime: "12 months",
    remainingtime: "6 months",
    progressreport: 60,
    status: "delayed",
    priority: "MEDIUM",
  }
]