export const demmyPrograms = [
  {
    id: "TASK-8782",
    program: "Program 1",
    programmanager: "Bemnet Adugna",
    budget: "232,000 Birr",
    time: "12 months",
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    program: "Program 2",
    programmanager: "Bemnet Adugna",
    budget: "1,000,000.00 Birr",
    time: "12 months",
    status: "completed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    program: "Program 3",
    programmanager: "Bemnet Adugna",
    budget: "152 Laptops",
    time: "12 months",
    status: "delayed",
    priority: "LOW",
  },
  {
    id: "TASK-8782",
    program: "Program 1",
    programmanager: "Bemnet Adugna",
    budget: "232,000 Birr",
    time: "12 months",
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    program: "Program 2",
    programmanager: "Bemnet Adugna",
    budget: "1,000,000.00 Birr",
    time: "12 months",
    status: "delayed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    program: "Program 3",
    programmanager: "Bemnet Adugna",
    budget: "152 Laptops",
    time: "12 months",
    status: "completed",
    priority: "LOW",
  },
  {
    id: "TASK-8782",
    program: "Program 1",
    programmanager: "Bemnet Adugna",
    budget: "232,000 Birr",
    time: "12 months",
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    program: "Program 2",
    programmanager: "Bemnet Adugna",
    budget: "1,000,000.00 Birr",
    time: "12 months",
    status: "delayed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    program: "Program 3",
    programmanager: "Bemnet Adugna",
    budget: "152 Laptops",
    time: "12 months",
    status: "delayed",
    priority: "LOW",
  },
  {
    id: "TASK-8782",
    program: "Program 1",
    programmanager: "Bemnet Adugna",
    budget: "232,000 Birr",
    time: "12 months",
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    program: "Program 2",
    programmanager: "Bemnet Adugna",
    budget: "1,000,000.00 Birr",
    time: "12 months",
    status: "completed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    program: "Program 3",
    programmanager: "Bemnet Adugna",
    budget: "152 Laptops",
    time: "12 months",
    status: "delayed",
    priority: "LOW",
  },
  {
    id: "TASK-8782",
    program: "Program 1",
    programmanager: "Bemnet Adugna",
    budget: "232,000 Birr",
    time: "12 months",
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    program: "Program 2",
    programmanager: "Bemnet Adugna",
    budget: "1,000,000.00 Birr",
    time: "12 months",
    status: "delayed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    program: "Program 3",
    programmanager: "Bemnet Adugna",
    budget: "152 Laptops",
    time: "12 months",
    status: "delayed",
    priority: "LOW",
  },
  {
    id: "TASK-8782",
    program: "Program 1",
    programmanager: "Bemnet Adugna",
    budget: "232,000 Birr",
    time: "12 months",
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    program: "Program 2",
    programmanager: "Bemnet Adugna",
    budget: "1,000,000.00 Birr",
    time: "12 months",
    status: "delayed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    program: "Program 3",
    programmanager: "Bemnet Adugna",
    budget: "152 Laptops",
    time: "12 months",
    status: "delayed",
    priority: "LOW",
  },
  {
    id: "TASK-8782",
    program: "Program 1",
    programmanager: "Bemnet Adugna",
    budget: "232,000 Birr",
    time: "12 months",
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    program: "Program 2",
    programmanager: "Bemnet Adugna",
    budget: "1,000,000.00 Birr",
    time: "12 months",
    status: "delayed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    program: "Program 3",
    programmanager: "Bemnet Adugna",
    budget: "152 Laptops",
    time: "12 months",
    status: "delayed",
    priority: "LOW",
  },
  {
    id: "TASK-8782",
    program: "Program 1",
    programmanager: "Bemnet Adugna",
    budget: "232,000 Birr",
    time: "12 months",
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    program: "Program 2",
    programmanager: "Bemnet Adugna",
    budget: "1,000,000.00 Birr",
    time: "12 months",
    status: "delayed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    program: "Program 3",
    programmanager: "Bemnet Adugna",
    budget: "152 Laptops",
    time: "12 months",
    status: "delayed",
    priority: "LOW",
  },
  {
    id: "TASK-8782",
    program: "Program 1",
    programmanager: "Bemnet Adugna",
    budget: "232,000 Birr",
    time: "12 months",
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    program: "Program 2",
    programmanager: "Bemnet Adugna",
    budget: "1,000,000.00 Birr",
    time: "12 months",
    status: "delayed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    program: "Program 3",
    programmanager: "Bemnet Adugna",
    budget: "152 Laptops",
    time: "12 months",
    status: "delayed",
    priority: "LOW",
  },
  {
    id: "TASK-8782",
    program: "Program 1",
    programmanager: "Bemnet Adugna",
    budget: "232,000 Birr",
    time: "12 months",
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    program: "Program 2",
    programmanager: "Bemnet Adugna",
    budget: "1,000,000.00 Birr",
    time: "12 months",
    status: "delayed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    program: "Program 3",
    programmanager: "Bemnet Adugna",
    budget: "152 Laptops",
    time: "12 months",
    status: "completed",
    priority: "LOW",
  },
  {
    id: "TASK-8782",
    program: "Program 1",
    programmanager: "Bemnet Adugna",
    budget: "232,000 Birr",
    time: "12 months",
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    program: "Program 2",
    programmanager: "Bemnet Adugna",
    budget: "1,000,000.00 Birr",
    time: "12 months",
    status: "delayed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    program: "Program 3",
    programmanager: "Bemnet Adugna",
    budget: "152 Laptops",
    time: "12 months",
    status: "delayed",
    priority: "LOW",
  },
  {
    id: "TASK-8782",
    program: "Program 1",
    programmanager: "Bemnet Adugna",
    budget: "232,000 Birr",
    time: "12 months",
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    program: "Program 2",
    programmanager: "Bemnet Adugna",
    budget: "1,000,000.00 Birr",
    time: "12 months",
    status: "delayed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    program: "Program 3",
    programmanager: "Bemnet Adugna",
    budget: "152 Laptops",
    time: "12 months",
    status: "delayed",
    priority: "LOW",
  },
  {
    id: "TASK-8782",
    program: "Program 1",
    programmanager: "Bemnet Adugna",
    budget: "232,000 Birr",
    time: "12 months",
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    program: "Program 2",
    programmanager: "Bemnet Adugna",
    budget: "1,000,000.00 Birr",
    time: "12 months",
    status: "delayed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    program: "Program 3",
    programmanager: "Bemnet Adugna",
    budget: "152 Laptops",
    time: "12 months",
    status: "delayed",
    priority: "LOW",
  },
  {
    id: "TASK-8782",
    program: "Program 1",
    programmanager: "Bemnet Adugna",
    budget: "232,000 Birr",
    time: "12 months",
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    program: "Program 2",
    programmanager: "Bemnet Adugna",
    budget: "1,000,000.00 Birr",
    time: "12 months",
    status: "delayed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    program: "Program 3",
    programmanager: "Bemnet Adugna",
    budget: "152 Laptops",
    time: "12 months",
    status: "delayed",
    priority: "LOW",
  },
  {
    id: "TASK-8782",
    program: "Program 1",
    programmanager: "Bemnet Adugna",
    budget: "232,000 Birr",
    time: "12 months",
    status: "inprogress",
    priority: "HIGH",
  },
  {
    id: "TASK-7878",
    program: "Program 2",
    programmanager: "Bemnet Adugna",
    budget: "1,000,000.00 Birr",
    time: "12 months",
    status: "delayed",
    priority: "MEDIUM",
  },
  {
    id: "TASK-7839",
    program: "Program 3",
    programmanager: "Bemnet Adugna",
    budget: "152 Laptops",
    time: "12 months",
    status: "delayed",
    priority: "LOW",
  },
]