export const reportsList = [
  {
    id: "TASK-8782",
    name: "PHASE 1",
    sentdate: "20-05-2023",
    senttime: "08:23",
    users: "John Doe",
    attachment: "file.pdf",
    status: "inprogress",
  },
  {
    id: "TASK-7878",
    name: "PHASE 2",
    sentdate: "20-05-2023",
    senttime: "08:23",
    users: "John Doe",
    attachment: "file.pdf",
    status: "completed",
  },
  {
    id: "TASK-7839",
    name: "PHASE 3",
    sentdate: "20-05-2023",
    senttime: "08:23",
    users: "John Doe",
    attachment: "file.pdf",
    status: "delayed",
  },
  {
    id: "TASK-8782",
    name: "PHASE 4",
    sentdate: "20-05-2023",
    senttime: "08:23",
    users: "John Doe",
    attachment: "file.pdf",
    status: "inprogress",
  },
  {
    id: "TASK-7878",
    name: "PHASE 5",
    sentdate: "20-05-2023",
    senttime: "08:23",
    users: "John Doe",
    attachment: "file.pdf",
    status: "delayed",
  },
  {
    id: "TASK-7839",
    name: "PHASE 6",
    sentdate: "20-05-2023",
    senttime: "08:23",
    users: "John Doe",
    attachment: "file.pdf",
    status: "completed",
  },
  {
    id: "TASK-8782",
    name: "PHASE 7",
    sentdate: "20-05-2023",
    senttime: "08:23",
    users: "John Doe",
    attachment: "file.pdf",
    status: "inprogress",
  },
  {
    id: "TASK-7878",
    name: "PHASE 10",
    sentdate: "20-05-2023",
    senttime: "08:23",
    users: "John Doe",
    attachment: "file.pdf",
    status: "delayed",
  }
]